[build]
  command = "npm run build"
  publish = "build" # Or your build output folder (e.g., dist for Vite or public for some frameworks)

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"
